export const ErrorCodes = {
  PAY_INVALID_AMOUNT: 'PAY_INVALID_AMOUND',
  PAY_INVALID_CURRENCY: 'PAY_INVALID_CURRENCY',
  PAY_INVALID_STATE_TRANSITION: 'PAY_INVALID_STATE_TRANSITIONS',
  PAY_TRANSACTION_NOT_FOUND: 'PAY_TRANSACTION_NOT_FOUND',
  IDEM_KEY_CONFLICT: 'IDEM_KEY_CONFLICT',
  PROV_UNSUPPORTED: 'PROV_UNSUPPORTED',
  PROV_API_ERROR: 'PROV_API_ERROR',
  PROV_DECLINED: 'PROV_DECLINED',
  PROV_UNAVAILABLE: 'PROV_UNAVAILABLE',
  PROV_INVALID_WEBHOOK_SIGNATURE: 'PROV_INVALID_WEBHOOK_SIGNATURE',
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_CACHE_ERROR: 'SYS_CACHE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
